apiVersion: v1
kind: Pod
metadata:
  name: nginx-Pod
  labels:
    app: web
spec:
  hostNetwork: false
  hostIPC: false
  hostPID: false
  containers:
    - name: nginx
      image: kaizheh/nginx
      securityContext:
        privileged: false
        capabilities:
          add:
            - NET_ADMIN
        readOnlyRootFilesystem: true
        runAsUser: 100
        runAsGroup: 1000
