apiVersion: v1
kind: Pod
metadata:
  name: docker-mount-pod
spec:
  containers:
    - name: docker-mount-container
      image: ubuntu
      command: ["sleep", "43200"]
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
